repos:
  # check code style
  - repo: https://github.com/psf/black
    rev: 21.4b1
    hooks:
      - id: black
  # check imports sort
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [ toml ]
        exclude: ^.*/?setup\.py$
  # code errors and complexity
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies: [ toml ]
  # check equaling to PEP8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: [ --no-ensure-ascii ]
      - id: check-yaml
        exclude: ^tests/.*
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*/frontend/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*/frontend/.*
      - id: debug-statements
  # type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
