version: "3.8"

services:
  course_application:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - course_application.env
    entrypoint: uwsgi --ini ./app/production.ini
  course_proxy_server:
    image: nginx
    ports:
      - 80:80
    links:
      - course_application
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
